### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cuongvng** [monkiravn/AssignmentDS#1]
SQL Task 6: thiếu `FROM` table nào: "SELECT COUNT(CITY) - COUNT(DISTINCT CITY);"

Task 7: Cần tách ra 2 câu query riêng biệt.

**Comment by monkiravn** [comment]
Hi anh Cường,
Cám ơn anh đã giúp em nhận ra lỗi sai.

Vào CN, 13 thg 9, 2020 vào lúc 20:05 Cuong V. Nguyen <
notifications@github.com> đã viết:
